package org.example.warehousemcs.Dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class WarehouseDTO {

    // Added id because your error starts with a Long parameter
    private Long id;

    private String warehouseCode;
    private String name;
    private String managerName;
    private String location;
    private String address;
    private String city;
    private String state;
    private String country;
    private String zipCode;
    private String email;

    // Changed to Double to match the 12th and 13th parameters in your error
    private Double capacity;
    private Double currentUtilization;

    private String status;
    private Boolean active;

    // These are usually excluded from 'new' constructor queries
    // because they are generated by the DB/Hibernate
    private String tenantId;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}